### ISSUE TITLE
Add Serialization

### ISSUE THREAD

**Issue by debop** [lauris/awesome-scala#103]
Fast Serialization - Ultra fast serialzation library - performace above than binary or kryo

[FST](https://github.com/RuedigerMoeller/fast-serialization)
[Benchmark](https://github.com/RuedigerMoeller/fast-serialization/wiki/Benchmark)

**Comment by longcao** [comment]
While this indeed looks useful for Scala developers, it looks like it's all Java, thus I don't think it should be added into this list. Anyone else have an opinion?

**Comment by non** [comment]
I agree with @longcao, the entry probably belongs in awesome-jvm or awesome-java.
