### ISSUE TITLE
Any soap framework for scala?

### ISSUE THREAD

**Issue by chenrui333** [lauris/awesome-scala#126]
I searched the page and did not find any lib related to SOAP framework.

**Comment by zarthross** [comment]
I think you're looking for http://scalaxb.org/

**Comment by chenrui333** [comment]
@zarthross thank you, I will take a look at it.

**Comment by d1egoaz** [comment]
Maybe you can try this:
http://downloads.typesafe.com/rp/play-soap/Home.html

**Comment by zarthross** [comment]
forgetting
