### ISSUE TITLE
FRP: SynapseGrid

### ISSUE THREAD

**Issue by Primetalk** [lauris/awesome-scala#152]
## Functional Reactive Programming

...
* [SynapseGrid](https://github.com/Primetalk/SynapseGrid) — an FRP framework for constructing reactive real-time immutable data flow systems. It implements an original way of running and organizing event-driven systems based on Petri nets. The topology can be viewed as a .dot graph. The library is compatible with Akka and can seamlessly communicate with other actors.

**Comment by longcao** [comment]
@Primetalk looks pretty cool- feel free to open a pull request adding this as an entry!

**Comment by longcao** [comment]
Closed by #153. Thanks!

**Comment by Primetalk** [comment]
Thanks to you!
