### ISSUE TITLE
Add http4s

### ISSUE THREAD

**Issue by mfirry** [lauris/awesome-scala#165]
http://http4s.org/

**Comment by longcao** [comment]
@mfirry thanks for the submissions! Feel free to open a PR for these (try to follow how it looks currently)

**Comment by mfirry** [comment]
Alright. Shoud I also add ★ and ⧗?

**Comment by longcao** [comment]
@mfirry don't worry about those - we have a script that we run periodically to populate those fields.

**Comment by longcao** [comment]
closed by #166
