### ISSUE TITLE
JSON Manipulation link broken

### ISSUE THREAD

**Issue by saraiva132** [lauris/awesome-scala#182]
There is no JSON Manipulation header nor does a link exist. I might even suggest to add the following libraries:

Jawn - Fast json parser (According to them competetive with java gson/jackson speed)
https://github.com/non/jawn
sonofjson - A Scala library for dealing with JSON in a way that makes it almost feel native. 
https://github.com/wspringer/sonofjson

**Comment by saraiva132** [comment]
If you want i can add a PR when i get home,

**Comment by longcao** [comment]
@saraiva132 a pull request would be much appreciated! We can call this section "JSON" for all these json related libs.
