### ISSUE TITLE
Good book to learn Scala

### ISSUE THREAD

**Issue by lopezavila85** [lauris/awesome-scala#210]
I have followed Programming Scala, 2nd Edition, by Dean Wampler and Alex Payne:
http://shop.oreilly.com/product/0636920033073.do

It contains a great overview of the features in Scala. In my case, I would like to learn Spark so this book has helped me to being introduced into the Scala world

**Comment by longcao** [comment]
feel free to submit a pull request! (and perhaps a new books section might be called for?)

**Comment by SethTisue** [comment]
please send a pull request
