### ISSUE TITLE
Casbah legacy

### ISSUE THREAD

**Issue by box3x4** [lauris/awesome-scala#299]
Hi guys! Great job centralizing all this material, really cool!

In the database section, Casbah is listed as the official suported scala driver for MongoDB, but that's no longer the case. The new officialy suported driver is the MongoDB Scala Driver(https://github.com/mongodb/mongo-scala-driver) as indicated in their site.

Thanks for the awesome repository!

**Comment by longcao** [comment]
@box3x4 Good heads up! Feel free to fork and open a PR and I'll get that merged.

**Comment by SethTisue** [comment]
please send a pull request
