### ISSUE TITLE
Github things that awesome-scala contains Python sources.

### ISSUE THREAD

**Issue by frgomes** [lauris/awesome-scala#321]
I've forked awesome-scala (for the sake of 'bookmarking' it, really!) and today I've noticed that Github thinks that my fork is made of Python sources, so I suppose the same applies to the original thing too.

I cannot change the type of my fork fork apparently and so... maybe the type could be changed in the original project.

**Comment by ScalaWilliam** [comment]
What is your expectation?

**Comment by longcao** [comment]
This is pretty much because of https://github.com/lauris/awesome-scala/blob/master/metadata.py - GitHub counts that as "source", and since this repo is pretty much a Markdown file and this python script, this lines up.

**Comment by sake92** [comment]
Github uses [linguist](https://github.com/github/linguist) library to detect languages.  
You can add a `.gitattributes` file with git-style path matchers for the files you want to ignore.  
For example:
`metadata.py linguist-vendored` or `folder-to-ignore/* linguist-vendored` 

I don't know how will it classify this repo if there is no files with code? Try and see..

**Comment by SethTisue** [comment]
this seems unimportant. if someone steps up with some kind of pull request on this great, but I don't see a reason to keep the issue open
