### ISSUE TITLE
Revise SCrypto description

### ISSUE THREAD

**Issue by jmcardon** [lauris/awesome-scala#345]
I'd like to propose to revise SCrypto to
```
SCrypto: Cryptographic primitives for blockchain & other cryptocurrencies
```

It is most certainly not an All-purpose cryptography library. It's missing encryption, many types of signing algorithms, authentication, password hashing, and more utilities; All things that should be included in a library that is supposed to be a general cryptography library. 

It exists to support scorex, which is a framework for cryptocurrencies itself.

TSec is a general cryptography library, which includes most of the cryptographic primitives (a list that is continually growing), but does not include the cryptographic data structures SCrypto does.

Note that I don't mean to speak ill of SCrypto or the great work its authors have done, but rather that SCrypto is more of a cryptography library for a very specific use case, specifically related to cryptocurrencies and hashing.

**Comment by SethTisue** [comment]
SGTM, please send a pull request
