### ISSUE TITLE
Cool JSON and HTTP libraries

### ISSUE THREAD

**Issue by gorros** [lauris/awesome-scala#386]
Please add these HTTP and JSON libraries:

- [uPickle: a simple Scala JSON serialization library](https://github.com/lihaoyi/upickle)

- [A Scala port of the popular Python Requests HTTP client: flexible, intuitive, and straightforward to use.
](https://github.com/lihaoyi/requests-scala)

**Comment by longcao** [comment]
Hey! Feel free to open a PR against this repo, I think `uJson` has an entry already though.

**Comment by SethTisue** [comment]
please send a pull request
