### ISSUE TITLE
maintainers wanted

### ISSUE THREAD

**Issue by SethTisue** [lauris/awesome-scala#431]
would you like to help respond to and merge issues and pull requests in this repo? currently @longcao and I have merge powers, but we're both pretty busy with other stuff and would love to have additional maintainers involved

**Comment by rumeshkrish** [comment]
Hi, I am willing to join with you.

**Comment by SethTisue** [comment]
@rumeshkrish great! looks like you're new here, so why not stick around for a while, responding to issues and pull requests and so on, and after we've gotten to know each other a little, we'll see about actual merge rights?

**Comment by rumeshkrish** [comment]
@SethTisue Perfect! I am at beginning stage, It's better to understand the activity and get familiar with this.

**Comment by SethTisue** [comment]
see also #435

**Comment by agaro1121** [comment]
I'm happy to stick around and help out as well
