### ISSUE TITLE
Re-alphabetize

### ISSUE THREAD

**Issue by SethTisue** [lauris/awesome-scala#434]
re-alphasort within sections as they've gone out of order

@longcao wrote on #307:

> or figure out a better way to list entries if there is, but I don't think I would want to sort by stars and bias towards the projects that already have a lot)

**Comment by raj-parekh** [comment]
Hi Seth
I can help here.

**Comment by raj-parekh** [comment]
submitted a PR. I wrote small script to sort everything in order. Still need to work on it. I'll come up with something.

**Comment by SethTisue** [comment]
fixed by #437 

re: more automation, at the time I opened this ticket I didn't know about #435 yet, the problem may already be solved there
