### ISSUE TITLE
print() is a function in Python 3

### ISSUE THREAD

**Issue by cclauss** [lauris/awesome-scala#452]
[flake8](http://flake8.pycqa.org) testing of https://github.com/lauris/awesome-scala on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./metadata.py:60:31: E999 SyntaxError: invalid syntax
        print '    {0}/{1}: ok'.format(owner, name)
                              ^
1     E999 SyntaxError: invalid syntax
1
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by SethTisue** [comment]
would you like to PR a fix....?
