### ISSUE TITLE
Does this can be considered if the development has been completed?

### ISSUE THREAD

**Issue by pckrishnadas88** [lauris/awesome-scala#492]
It is currently WIP. library similar to underscore js or loadash.

https://github.com/pckrishnadas88/underscore-scala

I know this is not an issue, but would like to get a feedback from the community so that I can go forward.

**Comment by SethTisue** [comment]
I think it's better to restrict it to completed libraries. I'd suggest using other means (for example, https://users.scala-lang.org) to get the word out about a WIP library and get feedback.
