### ISSUE TITLE
Add ScalaCollider

### ISSUE THREAD

**Issue by Sciss** [lauris/awesome-scala#62]
[ScalaCollider](https://github.com/Sciss/ScalaCollider) is a sound synthesis library based on SuperCollider. Categories: Music, Sound

**Comment by Sciss** [comment]
Do you need any additional information?

**Comment by longcao** [comment]
@Sciss hey - sorry about that, must have missed this somehow. Feel free to open a PR against the repo!

**Comment by Sciss** [comment]
Thanks, appreciated!
